### ISSUE TITLE
Symlink cycle in submodule

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/cli11#1]
I looked into the symlink-caused cycle in the CLI11 submodule and there is indeed one:

```
warning: directory cycle caused by symlink build/.bpkg/tmp/78c1e67e6423/upstream/tests/mesonTest/subprojects/CLI11/
  info: symlink target build/.bpkg/tmp/78c1e67e6423/upstream/
```

I've reported this to the upstream: https://github.com/CLIUtils/CLI11/issues/696

While in `build2` 0.14.0 this cases an error, in 0.15.0 we now handle it better and just issue the above warning (as long as we don't "import" such cycles into the package). I think it makes sense to switch back to the submodule setup since (1) it will become a non-issue once 0.15.0 is release and (2) it doesn't affect the archive (for CI you can use the stage service in the meaning by passing `--server https://ci.stage.build2.org` to `bdep-ci`). In fact, your commit eebeef7b419 looks exactly how I would have done it.

**Comment by EmilRosenquist** [comment]
This has been fixed in upstream and I now use symlinks in https://github.com/build2-packaging/cli11/pull/4

**Comment by EmilRosenquist** [comment]
Solved in https://github.com/build2-packaging/cli11/pull/4 , closing issue.
