### ISSUE TITLE
Various issues with submitted 2.1.2 package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/cli11#2]
Copying the issues from the chat so that they don't get lost:

1. `option_type.test` -- by convention Testscript files are either called `testscript` or with the `.testscript` extension (and if you rename this file to `option_type.testscript`, then you can use `testscript{option_type}` in the `buildfile`).

2. Installation does not recreate the `CLI` subdirectory.

3. `WindowsTest` should not be excluded with an `if` but rather with `include = false` so that it ends up in the distribution.

**Comment by EmilRosenquist** [comment]
2 and 3 is addressed in #4, Not sure if 1 is applicable any longer.
