### ISSUE TITLE
Consider moving tests into a separate package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/cli11#3]
I've noticed that this package depends on `catch2` that is only used in test (and thus an unnecessary dependency unless and until tests are run). The recommended way to handle such cases is to create a separate `-tests` package as described in this HOWTO: https://github.com/build2/HOWTO/blob/master/entries/handle-tests-with-extra-dependencies.md

**Comment by EmilRosenquist** [comment]
I split it up in https://github.com/build2-packaging/cli11/pull/4

**Comment by EmilRosenquist** [comment]
Solved in #4 , closing issue.
